### ISSUE TITLE
 Cannot find module 'aws-sdk' when creating the lambda

### ISSUE THREAD

**Issue by xpepper** [christian-fei/lambda-status#1]
When creating the lambda I got this error

```
./node_modules/.bin/claudia create --region eu-central-1 --handler lambda.handler 
validating package
Error: Cannot find module 'aws-sdk'
```

The solution should be to explicitly add 'aws-sdk' as a dependency in package.json

```
npm i aws-sdk --save
```

**Comment by christian-fei** [comment]
Thank you!

**Comment by christian-fei** [comment]
Fixed with https://github.com/christian-fei/lambda-status/commit/c84bcbe6eb5b905b5526c262d2e01229ad4fca24
